# Server
server:
    port: 8081

# Spring
spring:
    application:
        name: processador-video
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: none
    servlet:
        multipart:
            enabled: true
            max-file-size: 200MB
            max-request-size: 200MB
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}

# Caminho temporário dos frames
storage:
    temp-directory: /tmp/frames
    s3:
        bucket: fiap-videos-processados

cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: us-east-1

queue:
    video: videos-status
    zip: zips-gerados
