name: CD - Deploy to Docker and EKS

on:
  workflow_run:
    workflows: ["CI - Run Tests"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Docker and EKS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success' }}
    steps:

      #Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      #Configurar o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construir o JAR com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Configurar o DOCKER
      - name: Login to DockerHub
        run: docker login -u ar989827 -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir e enviar a imagem para o Docker Hub
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ar989827/processador-video:${{ github.sha }} \
            -t ar989827/processador-video:latest \
            --push .

      # Configurar kubectl para acessar o cluster EKS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name dev-fiap-eks-cluster --region us-east-1

      # Atualizar deployment no EKS
      - name: Update Deployment
        run: |
          kubectl set image deployment/processador-deployment processador-container=ar989827/processador-video:${{ github.sha }}
          kubectl rollout status deployment/processador-deployment